algoritmo "39-Contagem-Regressiva"
// CURSO EM VÍDEO - Algoritmos
// Professor: Gustavo Guanabara
// Aluno: Guilherme Alves
// Exercício: 39) Faça um algoritmo que mostre na tela a seguinte contagem: 10 9 8 7 6 5 4 3 Acabou!

var
   numero: inteiro

inicio
   numero <- 10

   enquanto (numero >= 3) faca
      escreva(numero)
      numero <- numero - 1
   fimenquanto
   
   escreval(" Acabou!")

fimalgoritmo