algoritmo "40-Contagem-Progressiva-3"
// CURSO EM VÍDEO - Algoritmos
// Professor: Gustavo Guanabara
// Aluno: Guilherme Alves
// Exercício: 40) Crie um aplicativo que mostre na tela a seguinte contagem: 0 3 6 9 12 15 18 Acabou!

var
   numero: inteiro

inicio
   numero <- 0

   enquanto (numero <= 18) faca
      escreva(numero)
      numero <- numero + 3
   fimenquanto

   escreval(" Acabou!")

fimalgoritmo