algoritmo "02-Boas-Vindas"
// CURSO EM VÍDEO - Algoritmos
// Professor: Gustavo Guanabara
// Aluno: Guilherme Alves
// Exercício: 2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boasvindas para ela.
// Exemplo:
// 1) Qual é o seu nome?
// 2) João da Silva
// 3) Olá João da Silva, é um prazer te conhecer!

var
  nome: caractere

inicio
   escreva("Qual é o seu nome? ")
   leia(nome)
   escreva("Olá ", nome ,", é um prazer te conhecer!")

fimalgoritmo