algoritmo "64-Numeros-Para"
// CURSO EM VÍDEO - Algoritmos
// Professor: Gustavo Guanabara
// Aluno: Guilherme Alves
// Exercício: 64) Desenvolva um programa usando a estrutura “para” que mostre na tela a seguinte contagem:
// 0 5 10 15 20 25 30 35 40 Acabou!

var
   numero: inteiro

inicio

   numero <- 0

   para numero de 0 ate 40 passo numero + 5 faca
      escreva(numero, " ")
   fimpara

   escreva("Abacou!")

fimalgoritmo