algoritmo "65-Contagem-Regressiva"
// CURSO EM VÍDEO - Algoritmos
// Professor: Gustavo Guanabara
// Aluno: Guilherme Alves
// Exercício: 65) Desenvolva um programa usando a estrutura “para” que mostre na tela a seguinte contagem:
// 100 90 80 70 60 50 40 30 20 10 0 Acabou!

var

   numero: inteiro

inicio

   numero <- 0

   para numero de 100 ate 0 passo (numero - 10) faca
      escreva(numero," ")
   fimpara

   escreva("Acabou!")

fimalgoritmo