algoritmo "38-Contagem-Progressiva"
// CURSO EM VÍDEO - Algoritmos
// Professor: Gustavo Guanabara
// Aluno: Guilherme Alves
// Exercício: 38) Escreva um programa que mostre na tela a seguinte contagem: 6 7 8 9 10 11 Acabou!

var
   numero: inteiro

inicio
   numero <- 6

   enquanto (numero <= 11) faca
      escreva(numero)
      numero <- numero + 1
   fimenquanto
   
   escreval(" Acabou!")

fimalgoritmo